server:
  port: 5200
  forward-headers-strategy: native
  error:
    include-message: always
spring:
  devtools:
    restart:
      enabled: false
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 database configuration.
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:${halo.work-dir}/db/halo
#    username: admin
#    password: 123456

      # MySQL database configuration.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  freemarker:
    suffix: .ftl
    settings:
      auto_import: /common/macro/global_macro.ftl as global
    template-loader-path:
#      - file:${halo.work-dir}/templates/
      - file:///${halo.work-dir}/templates/
      - classpath:/templates/
    expose-spring-macro-helpers: false
  data:
    redis:
      repositories:
        enabled: false
  redis:
    # Redis cache configuration.
    port: 6379
    database: 0
    host: 127.0.0.1
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
  health:
    redis:
      enabled: false
logging:
  level:
    run.halo.app: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${halo.work-dir}/logs

springfox:
  documentation:
    enabled: false

halo:
  download-timeout: 5m
#  memory 将数据缓存至内存，重启服务缓存将清空。
#  level 将数据缓存至本地，重启服务不会清空缓存。
#  redis 将数据缓存至 Redis，重启服务不会清空缓存，如需分布式部署 Halo，请选用此种缓存方式。
  cache: redis
#  work-dir: ./halo_theme/
  work-dir: ${user.home}/.halo/
